name: fastdvdnet
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=10.2
  - future=0.18.2
  - opencv=3.4.2
  - mkl=2020.4
  - pip=20.0.2
  - pycodestyle=2.5.0
  - pytest=5.4.1
  - python=3.6.10
  - pytorch=1.7.1
  - scikit-image=0.16.2
  - torchvision=0.8.2
  - pip:
    - tensorboardx==2.0
    - av==8.0.3

